"""Generate a submittable mindist script.

Mindist must see raw, unfitted, un-PBC-corrected coordinates: the whole point
is to measure the minimum distance between periodic images of the protein. It
is therefore never run inside the main pipeline, which produces only corrected
trajectories. Instead a standalone script is written that redoes the
concatenation from the original XTCs.
"""

from __future__ import annotations

import shlex
from pathlib import Path

from .config import TrajectoryEntry, format_interval, trajectory_start_times
from .gmx import header

TEMPLATE = """#!/bin/bash
# Auto-generated by modifyGMXtraj -- operates on RAW, unfitted coordinates so
# that periodic-image distances are meaningful. Do not point this at the
# PBC-corrected trajectory produced by the main pipeline.
#
# Submit with: sbatch {script_name}
# Edit the SBATCH header for your allocation before submitting.
#SBATCH -A {account}
#SBATCH -J mindist_{label}
#SBATCH -t {walltime}
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -o mindist_{label}.out

set -euo pipefail

GMX="{gmx}"
TPR="{tpr}"
NDX="{ndx}"
GROUP="{group}"
CUTDOWN_PS={cutdown_ps:g}
DISTANCE_NM={distance_nm:g}
RAW_COMBINED="{raw_combined}"
RAW_REDUCED="{raw_reduced}"
OUTPUT="{output}"

{concat_block}

echo "SYSTEM" | "$GMX" trjconv -f "$RAW_COMBINED" -s "$TPR" -n "$NDX" \\
    -o "$RAW_REDUCED" -dt "$CUTDOWN_PS" -quiet

echo "$GROUP" | "$GMX" mindist -f "$RAW_REDUCED" -s "$TPR" -n "$NDX" \\
    -od "$OUTPUT" -d "$DISTANCE_NM" -pi

rm -f "$RAW_COMBINED" "$RAW_REDUCED"

echo "Done. Periodic-image minimum-distance trace written to $OUTPUT"
echo "Inspect with: xmgrace $OUTPUT"
"""


def write_mindist_script(
    gmx: str,
    entries: list[TrajectoryEntry],
    reference_tpr: Path,
    index_file: Path,
    cutdown_ps: float,
    script_path: Path,
    account: str = "naiss2025-3-21",
    walltime: str = "01:00:00",
    distance_nm: float = 1.2,
    group: str = "PROTEIN",
) -> Path:
    header("Writing mindist submission script")

    raw_combined = "original_trajectories_for_mindist.xtc"
    raw_reduced = (
        f"original_trajectories_for_mindist_{format_interval(cutdown_ps)}ps.xtc"
    )
    output = "mindist_protein.xvg"

    if len(entries) == 1:
        concat_block = f'cp {shlex.quote(str(entries[0].trajectory))} "$RAW_COMBINED"'
    else:
        starts = trajectory_start_times(entries)
        file_list = " ".join(shlex.quote(str(e.trajectory)) for e in entries)
        settime_lines = "\n".join(f'echo "{t:g}"' for t in starts)
        concat_block = (
            "{\n" + settime_lines + "\n} | \"$GMX\" trjcat -f " + file_list
            + ' -o "$RAW_COMBINED" -settime -cat'
        )

    script_path.write_text(
        TEMPLATE.format(
            script_name=script_path.name,
            label=Path.cwd().name,
            account=account,
            walltime=walltime,
            gmx=gmx,
            tpr=str(reference_tpr),
            ndx=str(index_file),
            group=group,
            cutdown_ps=cutdown_ps,
            distance_nm=distance_nm,
            raw_combined=raw_combined,
            raw_reduced=raw_reduced,
            output=output,
            concat_block=concat_block,
        ),
        encoding="utf-8",
    )
    script_path.chmod(0o755)
    print(f"Wrote mindist script: {script_path}")
    print(f"Submit with: sbatch {script_path}")
    return script_path
